version: '3.1'
services:
# Customer Service
  customer:
    image: tomtan05/customer_service
    container_name: customer
    restart: on-failure
    ports:
      - "3001:3000"
# Mechanics Service
  mechanic:
    image: tomtan05/mechanics_service
    container_name: mechanic
    restart: on-failure
    ports:
      - "3002:3000"
# Notification Service
  request:
    image: tomtan05/request_service
    container_name: request
    restart: on-failure
    ports:
      - "3003:3000"
#Authentication Service
  authen:
    image: tomtan05/authen_service
    container_name: authen
    restart: on-failure
    ports:
      - "3004:3000"
#front-end
  payang_frontend:
    image: tomtan05/payang_frontend
    container_name: payang_frontend
    restart: on-failure
    ports:
     - "3005:3000"
# Prometheus
  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      ports:
        - '9090:9090'
      restart: always
# ApiGateWay
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    ports:
      - "80:8080"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - customer
      - mechanic
      - request
      - authen
      - payang_frontend
