version: '3.1'
services:
# Customer Service
  customer:
    image: tomtan05/customer_service
    container_name: customer
    restart: on-failure
    links:
        - mongo
    environment:
      WAIT_HOSTS: mongo:27017
      MONGOURL: mongodb://mongo:27017/payang
    ports:
      - "3000:3000"
# Mechanics Service
  mechanic:
    image: tomtan05/mechanics_service
    container_name: mechanic
    restart: on-failure
    links:
        - mongo
    environment:
      WAIT_HOSTS: mongo:27017
      MONGOURL: mongodb://mongo:27017/payang
    ports:
      - "3001:3000"
# Notification Service
  request:
    image: tomtan05/request_service
    container_name: request
    restart: on-failure
    links:
        - mongo
    environment:
      WAIT_HOSTS: mongo:27017
      MONGOURL: mongodb://mongo:27017/notification
    ports:
      - "3002:3000"
# Authentication Service
#  authen:
#    image: tomtan05/authen_service
#    container_name: authen
#    restart: on-failure
#    links:
#      - mongo
#    environment:
#      WAIT_HOSTS: mongo:27017
#      MONGOURL: mongodb://mongo:27017/payang
#    ports:
#      - "3003:3000"
# Database
  mongo:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - /data/db:/data/db
    ports:
      - '27017:27017'
# Seed data
  mongo-seed-customer:
    container_name: seed-data
    image: mongo
    links:
      - mongo
    volumes:
      - ./api/mockdata:/seed-data
    environment:
      WAIT_HOSTS: mongo:27017
    command:
      'bash -c "mongoimport --host mongo --db payang --collection customers --file /seed-data/customer.json
      &&
      mongoimport --host mongo --db payang --collection mechanics --file /seed-data/mechanics.json
      &&
      mongoimport --host mongo --db notification --collection mechanics --file /seed-data/notification.json
      "'
# Prometheus
  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      ports:
        - '9090:9090'
      restart: always
  node-exporter:
      image: prom/node-exporter:latest
      ports:
        - '9100:9100'
# ApiGateWay
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    ports:
      - "4200:8080"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - customer
      - mechanic
      - request
