version: '3.1'
services:
# Customer Service
  customer:
    image: tomtan05/customer_service:latest
    container_name: customer
    restart: on-failure
    ports:
      - "3001:3000"
# Mechanics Service
  mechanic:
    image: tomtan05/mechanics_service:latest
    container_name: mechanic
    restart: on-failure
    ports:
      - "3002:3000"
# Notification Service
  request:
    image: tomtan05/request_service:latest
    container_name: request
    restart: on-failure
    ports:
      - "3003:3000"
#Authentication Service
  authen:
    image: tomtan05/authen_service:latest
    container_name: authen
    restart: on-failure
    ports:
      - "3004:3000"
#front-end
  payang_frontend:
    image: tomtan05/payang_frontend:latest
    container_name: payang_frontend
    restart: on-failure
    ports:
     - "3005:3000"
# Prometheus
  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
        - prometheus_data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      ports:
        - '9090:9090'
      restart: always
# Grafana
  grafana:
    image: grafana/grafana:3.0.0-beta7
    volumes: 
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    ports:
      - "3006:3000"
# ApiGateWay
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: on-failure
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - customer
      - mechanic
      - request
      - authen
      - payang_frontend
#SSL
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"