version: '3'
services:
# Customer Service
  customer:
    image: customer_service:1.0
    container_name: customer
    links:
        - mongo
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - "3000:3000"
# Mechanics Service
  mechanic:
    image: mechanic_service:1.0
    container_name: mechanic
    links:
        - mongo
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - "3001:3000"
# Notification Service
  request:
    image: request_service:1.0
    container_name: request
    links:
        - mongo
    environment:
      WAIT_HOSTS: mongo:27017
    ports:
      - "3002:3000"
# Database
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
# Seed data
  mongo-seed-customer:
    container_name: seed-data
    image: mongo
    links:
      - mongo
    volumes:
      - ./api:/seed-data
    environment:
      WAIT_HOSTS: mongo:27017
    command:
      'bash -c "mongoimport --host mongo --db payang --collection customers --file /seed-data/customers.json
      &&
      mongoimport --host mongo --db payang --collection mechanics --file /seed-data/mechanics.json
      &&
      mongoimport --host mongo --db notification --collection mechanics --file /seed-data/notification.json
      "'
# Prometheus
  prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./etc/prometheus.yml:/etc/prometheus/prometheus.yml
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
      ports:
        - '9090:9090'
      restart: always
  node-exporter:
      image: prom/node-exporter:latest
      ports:
        - '9100:9100'
# ApiGateWay
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4200:8080"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - customer
      - mechanic
      - request
