version: 2
jobs:
  customer:
    docker:
      - image: node:11.13.0
    environment:
        WAIT_HOSTS: mongo:27017
    working_directory: ~/SOA2019_Group6/api/customer/
    steps:
      - checkout:
          path: ~/SOA2019_Group6
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
          name: Install Library
          command: |
                  npm install
      # run tests!
      - run: 
          name: run test
          command: |
                  npm test
      - setup_remote_docker:
          docker_layer_caching: true
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
                name: build image and push to docker hub
                command: |
                    docker login -u tomtan05 -p it59070062
                    docker build -t tomtan05/customer_service
                    docker push tomtan05/customer_service
      mongo:
        docker:
          - image: mongo
          - ports:
            - '27017:27017'
        working_directory: ~/SOA2019_Group6
        steps:
          - checkout:
            path: ~/SOA2019_Group6


workflows:
    version: 2
    complie:
        jobs:
            - mongo:
                filters:
                    branches:
                        only:
                            - master
            - customer:
                requires:
                  - mongo
                filters:
                    branches:
                        only:
                            - master
            