version: 2
jobs:
    customer:
        working_directory: ~/SOA2019_Group6/api/customer/
        docker:
            - image: circleci/node:11.13.0
        steps:
            - setup_remote_docker:
                docker_layer_caching: true
            - checkout:
                path: ~/SOA2019_Group6
            - run:
                name: Install Library
                command: |
                    npm install
            - run:
                name: Test Customer Service
                command: |
                    npm test
            - run:
                name: Build Docker Image
                command: |
                    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
                    docker build -t $DOCKER_USERNAME/customer_service .
                    docker push $DOCKER_USERNAME/customer_service

workflows:
    version: 2
    complie:
        jobs:
            - customer:
                filters:
                    branches:
                        only:
                            - master
            