version: 2
jobs:
  customer:
    working_directory: ~/SOA2019_Group6/api/customer/
    docker:
      - image: google/cloud-sdk
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout:
          path: ~/SOA2019_Group6
      - run:
          name: Config gcloud credentials
          command: |
            echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
            gcloud --quiet config set project ${GCLOUD_PROJECT_ID}
            gcloud auth configure-docker

workflows:
    version: 2
    complie:
        jobs:
            - customer:
                filters:
                    branches:
                        only:
                            - master
            