global: 
  external_labels: 
    monitor: test-monitor
  scrape_interval: 5s
scrape_configs: 
  - 
    job_name: authen_metrics
    metrics_path: /metrics
    static_configs: 
      - 
        targets: 
          - "https://payangonline.me/api/auth"