global: 
  external_labels: 
    monitor: test-monitor
  scrape_interval: 5s
scrape_configs: 
  - 
    job_name: authen_metrics
    metrics_path: /api/auth/metrics
    scheme: https
    static_configs: 
      - 
        targets: 
          - "payangonline.me"