global: 
  external_labels: 
    monitor: test-monitor
  scrape_interval: 5s
scrape_configs: 
  - 
    job_name: mechanics
    metrics_path: /api/mechanics
    static_configs: 
      - 
        targets: 
          - "localhost:4200"
  -
    job_name: node-exporter
    static_configs:
      -
        targets:
          - "node-exporter:9100"