global: 
  external_labels: 
    monitor: test-monitor
  scrape_interval: 5s
scrape_configs: 
  - 
    job_name: nginx
    metrics_path: /metrics
    static_configs: 
      - 
        targets: 
          - "35.198.223.251"